apiVersion: v1
kind: Secret
metadata:
  name: postgres.test.credentials.postgresql.acid.zalan.do
  namespace: test
type: Opaque
stringData:
  username: postgres
  password: postgres-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: standby.test.credentials.postgresql.acid.zalan.do
  namespace: test
type: Opaque
stringData:
  username: standby
  password: standby-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres.test-c1.credentials.postgresql.acid.zalan.do
  namespace: test
type: Opaque
stringData:
  username: postgres
  password: postgres-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: standby.test-c1.credentials.postgresql.acid.zalan.do
  namespace: test
type: Opaque
stringData:
  username: standby
  password: standby-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres.test-c2.credentials.postgresql.acid.zalan.do
  namespace: test
type: Opaque
stringData:
  username: postgres
  password: postgres-pass
---
apiVersion: v1
kind: Secret
metadata:
  name: standby.test-c2.credentials.postgresql.acid.zalan.do
  namespace: test
type: Opaque
stringData:
  username: standby
  password: standby-pass
